### ISSUE TITLE
BUG AudioSource not heared via SceneSwitcher

### ISSUE THREAD

**Issue by Mastercrrown** [exeldro/obs-source-switcher#1]
@Exeldro 

Hey i love your Scene Switcher, but i got a big problem about the audiosource. Even when i manually switch to the selected scene, while live streaming the sound source is correct and you can hear the audiosource. When i automate switch via sourceswitcher, it monitors the sound source at the bootom correctly, but while streaming no sound will be heard. I think there is a small BUG inside scene Switcher. Hopefully you can help me.

**Comment by sundnnstore** [comment]
I had the same problem,it seemed htis bugs still did not fix.

**Comment by neilisboa01** [comment]
Same for me.

**Comment by exeldro** [comment]
Can you test if https://github.com/exeldro/obs-source-switcher/actions/runs/605180222 fixes it?

**Comment by neilisboa01** [comment]
Yes, tested and working fine, audio gets to Youtube.

Thanks a lot!
