### ISSUE TITLE
Scenes Don't Deactivate / Audio Remains Active

### ISSUE THREAD

**Issue by EntranceJew** [exeldro/obs-source-switcher#2]
1. I created a scene that contains two deactivated sources, a browser source and a display capture.
2. I created a Source Switcher that has no events, no transitions, no timed switch. Just those two sources.
3. I create a hotkey for that Source Switcher's "Next" function.
4. I create a scene source in a new scene that references the scene the Source Switcher is in.
5. Pressing the hotkey to transfer from the display capture to the browser source works as expected, audio plays.
6. Pressing it again keeps the previous scene active so if it was creating audio in the audio mixer it would now continue to play audio when the desktop capture is visible.

A side effect of this is that scenes that were reliant on being deactivated / reactivated such as browser sources that are meant to unload do not do so therefore they can't be loaded again unless I do so manually in that referenced scene.

**Comment by exeldro** [comment]
should be fixed since version 0.2.8
